### Create field
POST http://localhost:8080/api/venues/3/fields
Authorization: fb3d24a0-3e01-422f-976b-1f95eaffd141
Content-Type: application/json

{
  "price": 100000,
  "type": "Futsal",
  "gallery": [
    {
      "photo_url": "https://example.com/photo1.jpg"
    },
    {
      "photo_url": "https://example.com/photo2.jpg"
    },
    {
      "photo_url": "https://example.com/photo3.jpg"
    }
  ]
}

### Get field
GET http://localhost:8080/api/venues/3/fields/4
Authorization: 6e2c539c-cae9-459a-88ce-62c9e657cd49

### Get field
GET http://localhost:8080/api/venues/3/fields
Authorization: f46e534f-7a19-4ba9-8983-fba535788238

### Delete field
DELETE http://localhost:8080/api/venues/3/fields/5
Authorization: 61603efa-31a1-485e-9652-5444df5b06b6

### Update field
PATCH http://localhost:8080/api/fields/5
Authorization: 61603efa-31a1-485e-9652-5444df5b06b6
Content-Type: application/json

{
  "price": 120000,
  "type": "Futsal",
  "gallery": [
    {
      "photo_url": "https://example.com/test1.jpg"
    },
    {
      "photo_url": "https://example.com/test2.jpg"
    },
    {
      "photo_url": "https://example.com/test3.jpg"
    }
  ],
  "fieldSchedules": [
    {"status": "not available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "not available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "not available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "not available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "not available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "not available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"},
    {"status": "available"}
  ]

}