### Create Venue
POST http://localhost:8080/api/venues
Authorization: b66c66be-2eee-4077-beaa-ec988cbb161b
Content-Type: application/json

{
  "name": "FitSpace Sports Arena",
  "phone_number": "+6281234567890",
  "street": "Jalan Raya Sport No. 123",
  "district": "Kecamatan Sporty",
  "city_or_regency": "Kota Atletik",
  "province": "Provinsi Kompetisi",
  "country": "Indonesia",
  "postal_code": "12345",
  "latitude": -6.200000,
  "longitude": 106.816666,
  "photoAddRequests": [
    {
      "photo_url": "testimoni/gambar",
      "description": "testimoni gambar"
    },
    {
      "photo_url": "testimoni/gambar2",
      "description": "testimoni gambar"
    },
    {
      "photo_url": "testimoni/gambar3",
      "description": "testimoni gambar"
    }
  ]
}

### Get Venue
GET http://localhost:8080/api/venues/2

### Update Venue
PATCH http://localhost:8080/api/venues/2
Authorization: b66c66be-2eee-4077-beaa-ec988cbb161b
Content-Type: application/json

{
  "name": "testUpdate",
  "phoneNumber": "+1234",
  "country": "testUpdate",
  "postalCode": "testUpdate",
  "latitude": -6.200000,
  "longitude": 106.816666,
  "gallery": [
    {
      "photo_url": "update/gambar2",
      "description": "update gambar"
    },
    {
      "photo_url": "update/gambar3",
      "description": "update gambar"
    }
  ]
}

### Delete Venue
DELETE http://localhost:8080/api/venues/1
Authorization: 625b20e9-2189-4574-82b9-e62024b3926c

### Get All Venue
GET http://localhost:8080/api/venues

### Get All Venue From Some Owner
GET http://localhost:8080/api/users/5/venues
Authorization: 625b20e9-2189-4574-82b9-e62024b3926c