### Create Venue
POST http://localhost:8080/api/venues
Authorization: daa1b1f2-849c-4942-9eb7-b1927ebfa70d
Content-Type: application/json

{
  "name": "FitSpace Sports Arena",
  "phone_number": "+6281234567890",
  "street": "Jalan Raya Sport No. 123",
  "district": "Kecamatan Sporty",
  "city_or_regency": "Kota Atletik",
  "province": "Provinsi Kompetisi",
  "postal_code": "12345",
  "latitude": -6.200000,
  "longitude": 106.816666
}

### Get Venue
GET http://localhost:8080/api/venues/4

### Update Venue
PATCH http://localhost:8080/api/venues/4
Authorization: daa1b1f2-849c-4942-9eb7-b1927ebfa70d
Content-Type: application/json

{
  "name": "FitSpace Sports Arena",
  "phone_number": "+6281234567890",
  "street": "Jalan Raya Sport No. 123",
  "district": "Kecamatan Sporty",
  "city_or_regency": "Kota Update"
}

### Delete Venue
DELETE http://localhost:8080/api/venues/4
Authorization: daa1b1f2-849c-4942-9eb7-b1927ebfa70d

### Get All Venue
GET http://localhost:8080/api/venues

### Get All Venue From Some Owner
GET http://localhost:8080/api/venues/owner
Authorization: 625b20e9-2189-4574-82b9-e62024b3926c